version: '3'

services:
  simple-java-file:
    image: simple-java-file
    build: simplejava/.

  manual-spring-boot:
    image: manual-dockerization-springboot
    stdin_open: true
    tty: true
    expose:
      - 9090
    ports:
      - "9090:8080"
    build: manual-dockerization-springboot/.

